services:
  mysql:
    image: mysql:8.0
    container_name: food-mysql
    ports:
      - "3307:3306"
    env_file:
      - .env.dev
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data: