spring:
  application:
    name: Food
  profiles: { include: secret, active: dev }
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  servlet:
    multipart:
      enabled: true               # 파일 업로드 활성화
      max-file-size: 10MB         # 파일 하나당 최대 크기
      max-request-size: 10MB      # 전체 요청 최대 크기 (여러 파일 합계)
      file-size-threshold: 2KB    # 메모리에 저장할 최소 크기

file:
  upload:
    dir: ./uploads    # 파일 저장 경로 (프로제트 루트 기준)
    max-file-count: 10      # 게시글당 최대 파일 개수

logging:
  level:
    root: INFO
    project.food: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

jwt:
  secret: ${jwt.secret}
  access-token-expiration: 1800000
  refresh-token-expiration: 604800000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true